version: 2.1
orbs:
  tfsec: mycodeself/tfsec@1.0.5
  go: circleci/go@1.10.0
jobs:
  tfsec:
    executor: tfsec/default
    steps:
      - checkout
      - tfsec/scan:
          directory: ./infrastructure
          exclude-checks: GEN001,GCP001,GCP002
  terratest:
    executor:
      name: go/default
      tag: '1.19.2'
    steps:
      - checkout
      - run: wget https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
      - run: sudo unzip terraform_1.8.3_linux_amd64.zip -d /usr/local/bin
      - run: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.5/terragrunt_linux_amd64
      - run: cp terragrunt_linux_amd64 terragrunt
      - run: sudo mv terragrunt /usr/local/bin/terragrunt
      - run: chmod u+x -R /usr/local/bin/terragrunt
      - run:
          name: terratest
          command: |
            cd terratest/test \
              && go mod init test \
              && go mod tidy \
              && go test -v -timeout 20m
workflows:
  analyze-tf-code:
    jobs:
      - tfsec
      - terratest