version: 2.1
orbs:
  tfsec: mycodeself/tfsec@1.0.5
  go: circleci/go@1.10.0
jobs:
  tfsec:
    executor: tfsec/default
    steps:
      - checkout
      - tfsec/scan:
          directory: ./infrastructure
          exclude-checks: GEN001,GCP001,GCP002
  terratest:
    executor:
      name: go/default
      tag: '1.19.2'
    steps:
      - checkout
      - run: wget https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
      - run: sudo unzip terraform_1.8.3_linux_amd64.zip -d /usr/local/bin
      - run: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.5/terragrunt_linux_amd64
      - run: cp terragrunt_linux_amd64 terragrunt
      - run: sudo mv terragrunt /usr/local/bin/terragrunt
      - run: chmod u+x -R /usr/local/bin/terragrunt
      - run:
          name: terratest
          command: |
            cd terratest/test \
              && go mod init test \
              && go mod tidy \
              && go test -v -timeout 20m
  templates-render:
    executor:
      name: go/default
      tag: '1.19.2'
    environment:
      customization_path: webserver-ec2-module-terraform/kubernetes/fluxcd/repositories/infra-repo/clusters/dev-cluster
      app_path: webserver-ec2-module-terraform/kubernetes/fluxcd/repositories/infra-repo/apps
      templates: webserver-ec2-module-terraform/templates
    steps:
      - run:
          name: Preinstall
          command: |
            git clone -b main --single-branch https://github.com/denis-dovgodko/webserver-ec2-module-terraform.git
            sudo apt-get update && sudo apt-get install -y gettext-base
      - run:
          name: Generate Output File
          command: |
            mkdir -p ${app_path}/${CIRCLE_BRANCH}
            envsubst < ${templates}/kustomization.yaml > "${customization_path}/${CIRCLE_BRANCH}.yaml"
            envsubst < ${templates}/gitrepository.yaml > "${app_path}/${CIRCLE_BRANCH}/gitrepository.yaml"
            envsubst < ${templates}/terraform.yaml > "${app_path}/${CIRCLE_BRANCH}/terraform.yaml"
      - run:
          name: Push Changes
          command: |
            cd webserver-ec2-module-terraform
            git config --global user.email "dendov555@gmail.com"
            git config --global user.name "denis-dovgodko"
            git add kubernetes/*
            git commit -am "[circle skip] Autogenerate"
            git push -q https://${GITHUB_TOKEN}@github.com/denis-dovgodko/webserver-ec2-module-terraform main
workflows:
  analyze-tf-code:
    jobs:
      - tfsec
      # - terratest:
      #     requires: 
      #       - tfsec
      - templates-render:
      #     requires: 
      #       - terratest
          filters:
            branches:
              ignore: 
              - main
          context: GITHUB_TOKEN