apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: prod
  namespace: flux-system
spec:
  vars:
  - name: environment_name
    value: production
  interval: 2m
  path: ./infrastructure
  sourceRef:
    kind: GitRepository
    name: prod
  approvePlan: auto
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: aws-credentials